version: '3.8'

services:
  graph-ql-server:
    image: saberguirat/graphql-go-server:${CI_COMMIT_SHA:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PORT: ${PORT:-8082}
    # ports:
    #   - 8082:${PORT:-8082}
    environment:
      MONGODB_URL: ${MONGODB_URL:-mongodb://root:example@mongo:27017}

  mongo:
    image: mongo:7.0.3-jammy
    restart: always
    # ports:
    #   - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db-data:/data/db

  mongo-express:
    image: mongo-express:1.0.0
    restart: always
    depends_on:
      - mongo
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD:-example}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL:-mongodb://root:example@mongo:27017}
      ME_CONFIG_SITE_BASEURL: ${MONGO_EXPRESS_BASEURL:-/database/administration}

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - graph-ql-server
      - mongo-express
volumes:
  mongo-db-data:
